version: '3.8'

services:
  app:
    build: .
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - postgres
    networks:
      - ferreteria-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ferreteria
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ferreteria-network

volumes:
  postgres_data:

networks:
  ferreteria-network:
    driver: bridge 